import Link from 'next/link';
import { SiteHeader } from '@/components/chrome';
import { Card, Measure } from '@/components/ui';
import { LayoutStudio } from '@/components/layout-studio';
import { getDesign, plantSites } from '@/lib/data';

export async function generateStaticParams() {
  return [{ id: 'dsg_7f2a' }, { id: 'dsg_2c81' }];
}

const keys = [
  ['Drag', 'Orbit around the design'],
  ['Wheel or pinch', 'Zoom in and out'],
  ['Right-drag', 'Pan the view'],
  ['Click a part', 'See its size, cost and build steps'],
  ['Arrow keys', 'Orbit without a pointer'],
  ['Plus and minus', 'Zoom without a pointer'],
];

export default async function ThreeDPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const design = getDesign(id);

  return (
    <>
      <SiteHeader variant="minimal" />
      <main id="main" className="mx-auto max-w-[1320px] px-4 py-6 sm:px-6">
        <div className="mb-4 flex flex-wrap items-end justify-between gap-3">
          <div>
            <Link href={`/designs/${design.id}`} className="label hover:text-ink">
              &larr; Back to the design
            </Link>
            <h1 className="mt-1.5 text-[28px]">{design.name} in 3D</h1>
          </div>
          <div className="flex flex-wrap gap-x-5 gap-y-1 text-sm text-ink-2">
            <span><Measure value={plantSites(design)} /> sites</span>
            <span><Measure value={design.layout.components.length} /> placed components</span>
            <span><Measure value="5.80 &times; 3.10 &times; 2.40" unit="m" /></span>
          </div>
        </div>

        <LayoutStudio design={design} fullBleed />

        <div className="mt-6 grid gap-4 lg:grid-cols-[1fr_1.4fr]">
          <Card className="p-5">
            <div className="label mb-3">Controls</div>
            <dl className="flex flex-col divide-y divide-line">
              {keys.map(([k, v]) => (
                <div key={k} className="flex items-baseline justify-between gap-4 py-2">
                  <dt className="measure text-xs text-ink">{k}</dt>
                  <dd className="text-right text-xs text-ink-2">{v}</dd>
                </div>
              ))}
            </dl>
          </Card>

          <Card className="p-5">
            <div className="label mb-2">Where this scene comes from</div>
            <p className="text-sm leading-relaxed text-ink-2">
              Nothing here was modelled by hand or generated by a model. Every mesh is drawn at the
              coordinates the layout already specifies, so the 3D view, the plan and the materials
              list are three renderings of one thing. A part cannot appear here without existing in
              the materials list, and a warning shown against a component was worked out for this
              space specifically.
            </p>
          </Card>
        </div>
      </main>
    </>
  );
}
