'use client';

import { useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import { Canvas } from '@react-three/fiber';
import { OrbitControls, Grid } from '@react-three/drei';
import * as THREE from 'three';
import type { Design, Layer, PlacedComponent, PlumbingRun } from '@/lib/types';

/**
 * The 3D scene.
 *
 * Nothing here is modelled by hand and nothing is generated by a model.
 * Every mesh is a projection of a PlacedComponent's real coordinates,
 * so the scene cannot disagree with the 2D plan or the materials list.
 *
 * Data space is millimetres with z up. Three.js is y up, so the mapping
 * is (x, z, y) and the whole scene is scaled to metres and centred.
 */

const S = 0.001; // millimetres to metres

const ROOM = { w: 5800, d: 3100, h: 2400 };

const palette: Record<Layer, string> = {
  shell: '#8a9a94',
  structure: '#4f6f66',
  plumbing: '#3f7f96',
  electrical: '#c08a2a',
  lighting: '#e2c887',
  plants: '#4e9a4a',
};

/** Explode moves each layer apart so the fit between parts becomes visible. */
const layerLift: Record<Layer, number> = {
  shell: 0, structure: 0.35, plumbing: -0.15, electrical: 1.1, lighting: 1.5, plants: 0.9,
};

function toScene(x: number, y: number, z: number): [number, number, number] {
  return [(x - ROOM.w / 2) * S, z * S, (y - ROOM.d / 2) * S];
}

function centreOf(c: PlacedComponent, i = 0): [number, number, number] {
  const step = c.instances?.step_mm ?? { x: 0, y: 0, z: 0 };
  return toScene(
    c.position_mm.x + step.x * i + c.size_mm.w / 2,
    c.position_mm.y + step.y * i + c.size_mm.d / 2,
    c.position_mm.z + step.z * i + c.size_mm.h / 2,
  );
}

/* ---------------- repeated geometry ---------------- */

function Repeated({
  component, explode, growth, selected, onSelect,
}: {
  component: PlacedComponent;
  explode: number;
  growth: number;
  selected: string | null;
  onSelect: (id: string) => void;
}) {
  const ref = useRef<THREE.InstancedMesh>(null);
  const count = component.instances?.count ?? 1;
  const isPlant = component.shape === 'plant';
  const scale = isPlant ? 0.35 + growth * 0.65 : 1;

  useLayoutEffect(() => {
    const mesh = ref.current;
    if (!mesh) return;
    const m = new THREE.Matrix4();
    const lift = layerLift[component.layer] * explode;
    for (let i = 0; i < count; i++) {
      const [x, y, z] = centreOf(component, i);
      m.makeScale(scale, scale, scale);
      m.setPosition(x, y + lift, z);
      mesh.setMatrixAt(i, m);
    }
    mesh.instanceMatrix.needsUpdate = true;
    mesh.computeBoundingSphere();
  }, [component, count, explode, scale]);

  const isSelected = selected === component.id;
  const colour = palette[component.layer];

  return (
    <instancedMesh
      ref={ref}
      args={[undefined, undefined, count]}
      onClick={(e) => { e.stopPropagation(); onSelect(component.id); }}
    >
      {isPlant ? (
        <icosahedronGeometry args={[(component.size_mm.w / 2) * S, 1]} />
      ) : (
        <cylinderGeometry args={[(component.size_mm.w / 2) * S, (component.size_mm.w / 2.6) * S, component.size_mm.h * S, 10]} />
      )}
      <meshStandardMaterial
        color={colour}
        roughness={isPlant ? 0.85 : 0.6}
        flatShading={isPlant}
        emissive={isSelected ? colour : '#000000'}
        emissiveIntensity={isSelected ? 0.5 : 0}
      />
    </instancedMesh>
  );
}

/* ---------------- single boxes ---------------- */

function Boxes({
  component, explode, selected, onSelect,
}: {
  component: PlacedComponent;
  explode: number;
  selected: string | null;
  onSelect: (id: string) => void;
}) {
  const count = component.instances?.count ?? 1;
  const isSelected = selected === component.id;
  const colour = palette[component.layer];
  const lift = layerLift[component.layer] * explode;
  const emissive = component.layer === 'lighting';

  return (
    <group>
      {Array.from({ length: count }).map((_, i) => {
        const [x, y, z] = centreOf(component, i);
        return (
          <mesh
            key={i}
            position={[x, y + lift, z]}
            onClick={(e) => { e.stopPropagation(); onSelect(component.id); }}
          >
            <boxGeometry
              args={[component.size_mm.w * S, component.size_mm.h * S, component.size_mm.d * S]}
            />
            <meshStandardMaterial
              color={colour}
              roughness={0.65}
              metalness={component.layer === 'structure' ? 0.25 : 0}
              transparent={component.id.startsWith('bench')}
              opacity={component.id.startsWith('bench') ? 0.55 : 1}
              emissive={isSelected ? colour : emissive ? colour : '#000000'}
              emissiveIntensity={isSelected ? 0.55 : emissive ? 0.4 : 0}
            />
          </mesh>
        );
      })}
    </group>
  );
}

/* ---------------- runs as swept tubes ---------------- */

function Run({ run, explode }: { run: PlumbingRun; explode: number }) {
  const geometry = useMemo(() => {
    const pts = run.points_mm.map((p) => new THREE.Vector3(...toScene(p.x, p.y, p.z)));
    const curve = new THREE.CatmullRomCurve3(pts, false, 'catmullrom', 0.02);
    return new THREE.TubeGeometry(curve, 96, (run.diameter_mm / 2) * S, 8, false);
  }, [run]);

  const lift = (run.kind === 'power' ? layerLift.electrical : layerLift.plumbing) * explode;
  const colour = run.kind === 'power' ? palette.electrical : palette.plumbing;

  return (
    <mesh geometry={geometry} position={[0, lift, 0]}>
      <meshStandardMaterial color={colour} roughness={0.5} />
    </mesh>
  );
}

/* ---------------- room shell ---------------- */

function Shell() {
  const w = ROOM.w * S;
  const d = ROOM.d * S;
  const h = ROOM.h * S;
  return (
    <group>
      <mesh position={[0, -0.005, 0]} rotation={[-Math.PI / 2, 0, 0]} receiveShadow={false}>
        <planeGeometry args={[w, d]} />
        <meshStandardMaterial color="#c9c8bd" roughness={1} />
      </mesh>
      <mesh position={[0, h / 2, -d / 2]}>
        <planeGeometry args={[w, h]} />
        <meshStandardMaterial color="#d8d7cc" roughness={1} side={THREE.DoubleSide} transparent opacity={0.5} />
      </mesh>
      <mesh position={[-w / 2, h / 2, 0]} rotation={[0, Math.PI / 2, 0]}>
        <planeGeometry args={[d, h]} />
        <meshStandardMaterial color="#d2d1c6" roughness={1} side={THREE.DoubleSide} transparent opacity={0.5} />
      </mesh>
      <lineSegments>
        <edgesGeometry args={[new THREE.BoxGeometry(w, h, d)]} />
        <lineBasicMaterial color="#8f9d96" transparent opacity={0.55} />
      </lineSegments>
    </group>
  );
}

/* ---------------- camera presets ---------------- */

export const cameraPresets: Record<string, [number, number, number]> = {
  isometric: [5.2, 3.8, 5.6],
  front: [0, 1.9, 8.2],
  side: [8.4, 1.9, 0],
  top: [0.01, 9.5, 0.01],
  doorway: [-3.4, 1.65, 5.4],
};

export type SceneSettings = {
  visible: Set<Layer>;
  explode: number;
  growth: number;
  phase: number;
  spin: boolean;
  preset: keyof typeof cameraPresets;
};

export function Scene3D({
  design, settings, selected, onSelect, className = '',
}: {
  design: Design;
  settings: SceneSettings;
  selected: string | null;
  onSelect: (id: string | null) => void;
  className?: string;
}) {
  const { visible, explode, growth, phase, spin, preset } = settings;

  // The canvas paints its own ground, so it has to follow the page theme
  // rather than sitting on a fixed colour in a dark interface.
  const [ground, setGround] = useState('#ecebe3');
  useEffect(() => {
    const read = () => {
      const v = getComputedStyle(document.documentElement)
        .getPropertyValue('--surface-2')
        .trim();
      if (v) setGround(v);
    };
    read();
    const mq = window.matchMedia('(prefers-color-scheme: dark)');
    mq.addEventListener('change', read);
    return () => mq.removeEventListener('change', read);
  }, []);

  const shown = design.layout.components.filter(
    (c) => visible.has(c.layer) && c.phase <= phase,
  );
  const shownRuns = design.layout.runs.filter((r) => {
    const layer: Layer = r.kind === 'power' ? 'electrical' : 'plumbing';
    return visible.has(layer) && r.phase <= phase;
  });

  return (
    <div className={className}>
      <Canvas
        dpr={[1, 1.75]}
        gl={{ antialias: true, preserveDrawingBuffer: false }}
        camera={{ position: cameraPresets[preset], fov: 38 }}
        onPointerMissed={() => onSelect(null)}
        frameloop={spin ? 'always' : 'demand'}
      >
        <color attach="background" args={[ground]} />
        <fog attach="fog" args={[ground, 13, 30]} />

        <hemisphereLight args={['#ffffff', '#9aa39c', 1.15]} />
        <directionalLight position={[6, 9, 4]} intensity={1.5} />
        <directionalLight position={[-5, 4, -3]} intensity={0.35} />

        {visible.has('shell') ? <Shell /> : null}

        <Grid
          args={[12, 12]}
          cellSize={0.5}
          cellThickness={0.5}
          cellColor="#b9b8ad"
          sectionSize={1}
          sectionThickness={0.9}
          sectionColor="#9aa8a1"
          fadeDistance={22}
          fadeStrength={1}
          followCamera={false}
          infiniteGrid
          position={[0, -0.004, 0]}
        />

        {shown.map((c) =>
          c.shape === 'cylinder' || c.shape === 'plant' ? (
            <Repeated
              key={c.id}
              component={c}
              explode={explode}
              growth={growth}
              selected={selected}
              onSelect={onSelect}
            />
          ) : (
            <Boxes key={c.id} component={c} explode={explode} selected={selected} onSelect={onSelect} />
          ),
        )}

        {shownRuns.map((r) => (
          <Run key={r.id} run={r} explode={explode} />
        ))}

        <OrbitControls
          makeDefault
          enableDamping
          dampingFactor={0.08}
          autoRotate={spin}
          autoRotateSpeed={0.9}
          minDistance={1.4}
          maxDistance={18}
          maxPolarAngle={Math.PI / 2 - 0.02}
          target={[0, 0.85, 0]}
        />
      </Canvas>
    </div>
  );
}
